in written

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -18,112 +18,51 @@ fi
 # for jq
 PATH=/usr/local/bin:$PATH
 
-payload=$(mktemp $TMPDIR/git-resource-request.XXXXXX)
+bin_dir="${0%/*}"
+if [ "${bin_dir#/}" == "$bin_dir" ]; then
+  bin_dir="$PWD/$bin_dir"
+fi
+
+payload=$(mktemp $TMPDIR/phabricator-pr-resource-request.XXXXXX)
 
 cat > $payload <&0
 
 load_pubkey $payload
-load_git_crypt_key $payload
-configure_https_tunnel $payload
 configure_git_ssl_verification $payload
 configure_credentials $payload
 
-uri=$(jq -r '.source.uri // ""' < $payload)
-# branch=$(jq -r '.source.branch // ""' < $payload)
-git_config_payload=$(jq -r '.source.git_config // []' < $payload)
-ref=$(jq -r '.version.ref // "HEAD"' < $payload)
-# depth=$(jq -r '(.params.depth // 0)' < $payload)
-# fetch=$(jq -r '(.params.fetch // [])[]' < $payload)
-submodules=$(jq -r '(.params.submodules // "all")' < $payload)
-submodule_recursive=$(jq -r '(.params.submodule_recursive // true)' < $payload)
-submodule_remote=$(jq -r '(.params.submodule_remote // false)' < $payload)
-commit_verification_key_ids=$(jq -r '(.source.commit_verification_key_ids // [])[]' < $payload)
-commit_verification_keys=$(jq -r '(.source.commit_verification_keys // [])[]' < $payload)
-gpg_keyserver=$(jq -r '.source.gpg_keyserver // "hkp://ipv4.pool.sks-keyservers.net/"' < $payload)
-# disable_git_lfs=$(jq -r '(.params.disable_git_lfs // false)' < $payload)
-clean_tags=$(jq -r '(.params.clean_tags // false)' < $payload)
-short_ref_format=$(jq -r '(.params.short_ref_format // "%s")' < $payload)
+repo_uri=$(jq -r '.source.repo_uri // ""' < $payload)
+diff=$(jq -r '.version.diff // 0' < $payload)
+version=$(jq -r '.version' < $payload)
+base=$(jq -r '.version.base // "HEAD"' < $payload)
+depth=$(jq -r '(.params.depth // 0)' < $payload)
 
 configure_git_global "${git_config_payload}"
 
-if [ -z "$uri" ]; then
-  echo "invalid payload (missing uri):" >&2
+if [ -z "$repo_uri" ]; then
+  echo "invalid payload (missing repo_uri):" >&2
   cat $payload >&2
   exit 1
 fi
 
+depthflag=""
+if test "$depth" -gt 0 2> /dev/null; then
+  depthflag="--depth $depth"
+fi
+
+
 if [ -d $destination ]; then
   cd $destination
   git reset --hard FETCH_HEAD
+  git pull
 else
-  git clone --single-branch $uri $destination --depth 1
+  git clone --single-branch $repo_uri $destination $depthflag
   cd $destination
 fi
 
-git fetch origin refs/tags/"$ref":refs/tags/"$ref"
-git checkout -q $ref
+concourse_git_resource__depth="$depth" \
+  "$bin_dir"/deepen_shallow_clone_until_ref_is_found "$base"
 
-invalid_key() {
-  echo "Invalid GPG key in: ${commit_verification_keys}"
-  exit 2
-}
+arc patch --diff $diff
 
-commit_not_signed() {
-  commit_id=$(git rev-parse ${ref})
-  echo "The commit ${commit_id} is not signed"
-  exit 1
-}
-
-if [ ! -z "${commit_verification_keys}" ] || [ ! -z "${commit_verification_key_ids}" ] ; then
-  if [ ! -z "${commit_verification_keys}" ]; then
-    echo "${commit_verification_keys}" | gpg --batch --import || invalid_key "${commit_verification_keys}"
-  fi
-  if [ ! -z "${commit_verification_key_ids}" ]; then
-    echo "${commit_verification_key_ids}" | \
-      xargs --no-run-if-empty -n1 gpg --batch --keyserver $gpg_keyserver --recv-keys
-  fi
-  git verify-commit $(git rev-list -n 1 $ref) || commit_not_signed
-fi
-
-git log -1 --oneline
-git clean --force --force -d
-
-if [ -f $GIT_CRYPT_KEY_PATH ]; then
-  echo "unlocking git repo"
-  git-crypt unlock $GIT_CRYPT_KEY_PATH
-fi
-
-if [ "$ref" == "HEAD" ]; then
-  return_ref=$(git rev-parse HEAD)
-else
-  return_ref=$ref
-fi
-
-# Store committer email in .git/committer. Can be used to send email to last committer on failed build
-# Using https://github.com/mdomke/concourse-email-resource for example
-git --no-pager log -1 --pretty=format:"%ae" > .git/committer
-
-# Store git-resource returned version ref .git/ref. Useful to know concourse
-# pulled ref in following tasks and resources.
-echo "${return_ref}" > .git/ref
-
-# Store short ref with templating. Useful to build Docker images with
-# a custom tag
-echo "${return_ref}" | cut -c1-7 | awk "{ printf \"${short_ref_format}\", \$1 }" > .git/short_ref
-
-# Store commit message in .git/commit_message. Can be used to inform about
-# the content of a successfull build.
-# Using https://github.com/cloudfoundry-community/slack-notification-resource
-# for example
-git log -1 --format=format:%B > .git/commit_message
-
-metadata=$(git_metadata)
-
-if [ "$clean_tags" == "true" ]; then
-  git tag | xargs git tag -d
-fi
-
-jq -n "{
-  version: {ref: $(echo $return_ref | jq -R .)},
-  metadata: $metadata
-}" >&3
+jq -n "{version: $(echo $version | jq)}" >&3
